import type React from "react"
import type { Metadata, Viewport } from "next"
import { Providers } from "./providers"
import { VoiceMicGated } from "@/components/voice-mic-gated"
import "./globals.css"

// (CSS width, CSS height, DPR, portrait pixel width, portrait pixel height)
// Matches public/splash/apple-splash-{pxW}x{pxH}.png generated by
// scripts/generate-pwa-assets.py.
const SPLASH_SCREENS: Array<{
  cssW: number
  cssH: number
  dpr: number
  pxW: number
  pxH: number
}> = [
  { cssW: 320, cssH: 568, dpr: 2, pxW: 640, pxH: 1136 },     // iPhone SE 1st gen
  { cssW: 375, cssH: 667, dpr: 2, pxW: 750, pxH: 1334 },     // iPhone 6/7/8
  { cssW: 414, cssH: 736, dpr: 3, pxW: 1242, pxH: 2208 },    // iPhone 6/7/8 Plus
  { cssW: 375, cssH: 812, dpr: 3, pxW: 1125, pxH: 2436 },    // iPhone X / XS / 11 Pro
  { cssW: 414, cssH: 896, dpr: 2, pxW: 828, pxH: 1792 },     // iPhone XR / 11
  { cssW: 414, cssH: 896, dpr: 3, pxW: 1242, pxH: 2688 },    // iPhone XS Max / 11 Pro Max
  { cssW: 360, cssH: 780, dpr: 3, pxW: 1080, pxH: 2340 },    // iPhone 12 mini
  { cssW: 390, cssH: 844, dpr: 3, pxW: 1170, pxH: 2532 },    // iPhone 12 / 13 / 14
  { cssW: 428, cssH: 926, dpr: 3, pxW: 1284, pxH: 2778 },    // iPhone 12 Pro Max / 14 Plus
  { cssW: 393, cssH: 852, dpr: 3, pxW: 1179, pxH: 2556 },    // iPhone 14 Pro
  { cssW: 430, cssH: 932, dpr: 3, pxW: 1290, pxH: 2796 },    // iPhone 14 Pro Max / 15 Pro Max
  { cssW: 402, cssH: 874, dpr: 3, pxW: 1206, pxH: 2622 },    // iPhone 16 Pro
  { cssW: 440, cssH: 956, dpr: 3, pxW: 1320, pxH: 2868 },    // iPhone 16 Pro Max
  { cssW: 768, cssH: 1024, dpr: 2, pxW: 1536, pxH: 2048 },   // iPad Mini
  { cssW: 834, cssH: 1194, dpr: 2, pxW: 1668, pxH: 2388 },   // iPad Pro 11"
  { cssW: 1024, cssH: 1366, dpr: 2, pxW: 2048, pxH: 2732 },  // iPad Pro 12.9"
]

const startupImages = SPLASH_SCREENS.map(({ cssW, cssH, dpr, pxW, pxH }) => ({
  url: `/splash/apple-splash-${pxW}x${pxH}.png`,
  media:
    `(device-width: ${cssW}px) and (device-height: ${cssH}px) ` +
    `and (-webkit-device-pixel-ratio: ${dpr}) and (orientation: portrait)`,
}))

export const metadata: Metadata = {
  title: "Kitchen Inventory",
  description: "Track your kitchen items, expiry dates, and recipes.",
  applicationName: "Kitchen Inventory",
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    title: "Kitchen Inventory",
    statusBarStyle: "black-translucent",
    startupImage: startupImages,
  },
  icons: {
    icon: [
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  other: {
    // Next 16's appleWebApp.capable already emits the modern
    // `mobile-web-app-capable`. The Apple-prefixed variant is still needed
    // for iOS versions before 17, so emit it explicitly here.
    "apple-mobile-web-app-capable": "yes",
  },
}

export const viewport: Viewport = {
  themeColor: "#f97316",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* First-paint background — matches splash so there is no white flash
            between the launch image and the React render. */}
        <style>{`html,body{background-color:#f97316}`}</style>
      </head>
      <body className="font-sans">
        <Providers>
          {children}
          {/* Voice mic button — gated server-side by feature_grants.voice_agent_enabled.
              Renders null for unauthenticated / non-granted users so no client bundle
              cost. Auto-hides when any overlay/sheet is open (Policy A, ADR 010). */}
          <VoiceMicGated />
        </Providers>
      </body>
    </html>
  )
}
